### PR TITLE
Bugfix: Windows 10 spawn ENOENT

### PR DESCRIPTION
**Pull request by tance77**
Fixing this issue.

https://github.com/bencevans/screenshot-desktop/issues/135

### CODE REVIEW

**Comment by navneetgarggate6** [comment]
I tried this changes but the issue still not solved.
image

**Comment by tance77** [comment]
"extraResources": [
        "node_modules/screenshot-desktop/lib/win32/screenCapture_1.3.2.bat",
        "node_modules/screenshot-desktop/lib/win32/app.manifest",
      ],

Try throwing these in your extra resources for windows in your package.json @navneetgarggate6

**Comment by tance77** [comment]
I don't have time to keep up to date with this project anymore. So I'm going to close the PR. Someone is more than welcome to reopen this PR.

**Comment by lucasltv** [comment]
Thanks @tance77 !!

**Pull request closed without merging**
