### PR TITLE
run correctly with bundlers

### PR DESCRIPTION
**Pull request by si458**
this patch simple copies the bat and manifest to a temp folder and runs it from there
this allows for it to work inside of node bundlers like PKG

### CODE REVIEW

**Comment by liuchengts** [comment]
It does work, I have changed index.js manually and this solved my problem

**Comment by bencevans** [comment]
Great, thanks for checking and letting us know. This has now been merged and released imminently.

**Comment by diksha-2020** [comment]
> Great, thanks for checking and letting us know. This has now been merged and released imminently.

Is it released ?

**Comment by diksha-2020** [comment]
Thanks for needful @bencevans 
Will check with the update .

**Pull request merged**
