### PR TITLE
Filename rather than buffer

### PR DESCRIPTION
**Pull request by bgschiller**
Allow passing a filename to the options, which writes the image to a file rather than reading it in.

For my use, I need to write the screenshot to a file. Without this patch, I need to call `screenshot()`, which (on some platforms) produces a temp file, then reads it, then deletes it. Then, I write the buffer to a file. This patch allows cutting many of those redundant steps.

(the diff will make more sense after #7 is merged. It's only the last few commits)

### CODE REVIEW

**Comment by bencevans** [comment]
Please could you update the README reflecting the filename opts and resolve conflicts?

**Comment by bencevans** [comment]
After which I'm happy to merge and release :rocket:

**Comment by bgschiller** [comment]
Good call. I added some more usage examples.

**Comment by bencevans** [comment]
Awesome! Have published to npm @ `v1.3.0`.

I don't suppose you've done much with the Windows Audio APIs? I've been trying to get programmatic control of the volume mixer without much luck thus far :pensive: I take it you've got a hand in on the C# front from the PR.

**Comment by bgschiller** [comment]
Thanks!

As far as knowing C# or windows APIs, I know approximately nothing. I got that screenCapture.bat to work basically through trial and error, and a lot of googling. Sorry I can't help ¯\\\_(ツ)_/¯

**Pull request merged**
